### ISSUE TITLE
Tom waits for an answer forever after winning the game 

### ISSUE THREAD

**Issue by ashimokawa** [littleprojects/Pebble_Lost_Contact#1]
This is quite annoying because the pebble keeps vibrating and bringing the game to foreground.

PS: Thanks for the game, hope you will find time to continue the story :+1:

**Comment by littleprojects** [comment]
Hi, 

did you have a pebble time or an older one? 

there should be only two short vibe pulse when the game starts. 

If you want, you can turn off the Vibration. When press enter on a incomming message a Settings-menu will open. 

First i will fix the bugs, and then i will continue the Story 😉 

thank you for the Report.

If you want. Please help me with the code or just testing. 

I have a normal pebble (black and White) i cant test it for the time or round…

greetings from Berlin,

David

Von: Andreas Shimokawa
Gesendet: ‎Samstag‎, ‎7‎. ‎Mai‎ ‎2016 ‎10‎:‎23
An: littleprojects/Pebble_Lost_Contact

This is quite annoying because the pebble keeps vibrating and bringing the game to foreground.

PS: Thanks for the game, hope you will find time to continue the story  :+1:

**Comment by ashimokawa** [comment]
I also have the original pebble.
What I meant is not that the vibration does not stop.
I meant that it is always reoccuring when the story is at the end and Tom is not dead.
Maybe I can look into the code and send a PR, if I have time later.

**Comment by littleprojects** [comment]
Ahh, now i know what you mean…

this is easy, i just Need to add a line on the right place to cancel all wakeups. 

thanks

Von: Andreas Shimokawa
Gesendet: ‎Sonntag‎, ‎8‎. ‎Mai‎ ‎2016 ‎15‎:‎54
An: littleprojects/Pebble_Lost_Contact
Cc: David Lenk, Comment

I also have the original pebble.
What I meant is not that the vibration does not stop.
I meant that it is always reoccuring when the story is at the end and Tom is not dead.
Maybe I can look into the code and send a PR, if I have time later.
